# Generated by Django 5.2.3 on 2025-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('principal_activo', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
            ],
        ),
    ]
