# Generated by Django 5.2.3 on 2025-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('prescribible', 'Producto Prescribible'), ('muestra', 'Muestra Médica'), ('promocional', 'Producto Promocional'), ('merch', 'Material Promocional / Merch')], default='prescribible', max_length=20),
        ),
    ]
