# Generated by Django 5.2.3 on 2025-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estatus',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
