# Generated by Django 5.2.3 on 2025-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_ruta_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('retraso', 'Retraso'), ('emergencia', 'Emergencia')], default='pendiente', max_length=50),
        ),
    ]
