# Generated by Django 4.2.25 on 2025-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_ruta_estatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['fecha_visita', 'doctor_id']},
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_visita_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('retraso', 'Retraso'), ('emergencia', 'Emergencia')], db_index=True, default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fecha_visita',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['usuario', 'fecha_visita'], name='rutas_ruta_usuario_ae1081_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['doctor', 'fecha_visita'], name='rutas_ruta_doctor__f1ab14_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['estatus', 'fecha_visita'], name='rutas_ruta_estatus_a4337a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('usuario', 'doctor', 'fecha_visita'), name='uniq_ruta_usuario_doctor_fecha'),
        ),
    ]
