# Generated by Django 5.2.3 on 2025-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='categoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
