# Generated by Django 5.2.3 on 2025-07-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_doctor_categoria_alter_doctor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
