# Generated by Django 5.2.3 on 2025-07-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_doctor_distrito_doctor_region'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='region',
        ),
        migrations.AddField(
            model_name='doctor',
            name='ubigeo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctores', to='ubicaciones.distrito'),
        ),
    ]
