# Generated by Django 5.2.3 on 2025-07-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0004_remove_doctor_distrito_remove_doctor_region_and_more'),
        ('productos', '0002_producto_tipo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_tam', models.PositiveIntegerField(verbose_name='Ranking por Tamaño de Mercado')),
                ('ms_tam', models.FloatField(verbose_name='Market Share por Tamaño')),
                ('rank_trim', models.PositiveIntegerField(verbose_name='Ranking Trimestral')),
                ('ms_trim', models.FloatField(verbose_name='Market Share Trimestral')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='doctores.doctor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'unique_together': {('doctor', 'producto')},
            },
        ),
    ]
