# Generated by Django 5.2.3 on 2025-08-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0006_doctor_visitador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='visitador',
        ),
    ]
