# Generated by Django 5.2.3 on 2025-07-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
