# Generated by Django 5.2.3 on 2025-07-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='productos_presentados',
        ),
        migrations.AddField(
            model_name='visita',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='ubicacion_final',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='ubicacion_inicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DetalleVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='visitas.visita')),
            ],
        ),
    ]
