# Generated by Django 5.2.3 on 2025-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_remove_visita_productos_presentados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
