# Generated by Django 5.2.3 on 2025-07-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='ubicacion_final',
        ),
    ]
