# Generated by Django 5.2.3 on 2025-07-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('visitas', '0004_remove_visita_ubicacion_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallevisita',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('muestra', 'Muestra Médica'), ('merch', 'Merchandising')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductoPresentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.visita')),
            ],
            options={
                'unique_together': {('visita', 'producto')},
            },
        ),
    ]
