# Generated by Django 5.2.3 on 2025-07-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        ('visitas', '0005_detallevisita_tipo_entrega_productopresentado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta'),
        ),
    ]
